name: build

on:
  push:
    branches: [ 1.19.2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: built
          path: fabric/build/libs
